version: '3'
networks:
  dev-net:
    driver: bridge
services:
  client-side:
    # build: .
    image: nginx
    container_name: client-side
    volumes:
      - /workspace/sirius-admin:/usr/share/nginx/html
    ports:
      - '9880:80'
      - '9840:443'
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_INDEX=index.html index.htm
    command:
      - /bin/bash
      - -c
      - "envsubst \"`printf '$${%s} ' $$(bash -c 'compgen -A variable')`\" < /usr/share/nginx/html/nginx/conf.d/site-template.conf > /etc/nginx/conf.d/front-end.conf && exec nginx -g 'daemon off;'"
    # command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /usr/share/nginx/html/nginx/conf.d/site-template.conf > /etc/nginx/conf.d/front-end.conf && exec nginx -g 'daemon off;'"
  server-side:
    image: nginx
    container_name: server-side
    ports:
      - '9980:80'
      - '9940:443'
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_INDEX=index.html index.htm
    command:
      - /bin/bash
      - -c
      - "envsubst \"`printf '$${%s} ' $$(bash -c 'compgen -A variable')`\" < /usr/share/nginx/html/nginx/conf.d/site-template.conf > /etc/nginx/conf.d/front-end.conf && exec nginx -g 'daemon off;'"
    # command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /usr/share/nginx/html/nginx/conf.d/site-template.conf > /etc/nginx/conf.d/front-end.conf && exec nginx -g 'daemon off;'"
  php-fpm:
    image: php:7.3-fpm
    container_name: php-fpm
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  redis:
    image: redis
    container_name: redis
    volumes:
      - /workspace/sirius-admin/docker/redis/data:/data
      - /workspace/sirius-admin/docker/redis/redis.conf:/etc/redis/redis.conf
